[tool.poetry]
name = "ai"
version = "0.0.1"
description = "This is AI Agent"
authors = ["Vimal Menon"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langsmith = "^0.3.10"
langchain = "^0.3.19"
langgraph = "^0.2.74"
pydantic = "^2.10.6"
langchain-ollama = "^0.2.3"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
tox = "^4.24.1"
mypy = "^1.15.0"
flake8 = "^7.1.2"
isort = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
app = "main:run"
