# Set the maximum line length to 79.
line-length = 100
target-version = "py311"

[lint]
# Add the `line-too-long` rule to the enforced rule set. By default, Ruff omits rules that
# overlap with the use of a formatter, like Black, but we can override this behavior by
# explicitly adding the rule.
# unfixable = ["F401"]
extend-select = ["E501"]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # # flake8-annotations
    # "ANN",
    # flake8-logging-format
    "LOG001",
    # flake8-implicit-str-concat
    "ISC001",

]
