name: Deploy and Release

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  build-deploy-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          echo deploy
