name: Deploy and Release

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

env:
  DOCKER_REGISTRY: vimalsmenon
  RELEASE: 0.0.18
  APP_NAME: ai.vimalmenon.com
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  # Single deploy job since we're just deploying
  build-deploy-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Docker push
        run: |
          docker build -t ${{ env.APP_NAME }}:${{ env.RELEASE }} .
          docker tag ${{ env.APP_NAME }}:${{ env.RELEASE }} ${{ env.DOCKER_REGISTRY }}/${{ env.APP_NAME }}:${{ env.RELEASE }}
          docker push ${{ env.DOCKER_REGISTRY }}/${{env.APP_NAME}}:${{ env.RELEASE }}
